### ISSUE TITLE
New-F5Session Errors when getting version

### ISSUE THREAD

**Issue by chrissmullins** [joel74/POSH-LTM-Rest#82] opened 2016-12-15 19:39 UTC
We are on F5 Version 12.1.1 and we get an authorization error when calling this:

$F5Version = Invoke-RestMethodOverride -Method Get -Uri "https://$LTMName/mgmt/tm/sys/version" -Credential $LTMCredentials -ContentType 'application/json'

We need the token that is created a few lines later.

**Comment by joel74** [comment] 2016-12-15 21:24
I'll check it out. Something must have changed between 12.1.0 and 12.1.1.

**Comment by chrissmullins** [comment] 2016-12-16 13:04
Awesome, thanks.  We also had to add 'loginProviderName' = 'tmos'

To this line in New-F5Session:

    $JSONBody = @{username = $LTMCredentials.username; password=$LTMCredentials.GetNetworkCredential().password; 'loginProviderName' = 'tmos'} | ConvertTo-Json

or we would get a 401 auth failure.

https://devcentral.f5.com/articles/demystifying-icontrol-rest-part-6-token-based-authentication

**Comment by joel74** [comment] 2016-12-20 05:11
Hi, Chris,
I'm wondering if it has to do with the permissions of the user whose credentials you're using to create the new F5 session, or if this is because it's an external account. For me, after upgrading to 12.1.1, New-F5Session still worked when a local account was used, but using an external (LDAP) account failed. I wonder if there's some issue with that external user doing a GET to retrieve the version info. I'll keep looking on my end, but could you confirm whether you're using a local or external account in the credentials you're passing in? Thanks.

**Comment by chrissmullins** [comment] 2016-12-20 16:23
Hi Joel,

I am definitely using an AD account.

Thanks,

Chris

**Comment by joel74** [comment] 2017-01-09 15:08
Chris,

Thanks for your patience over the holiday season. I confirmed that adding 'loginProviderName' = 'tmos' to the JSON does resolve part of the issue. The other part I'm working on is how to determine the LTM version before attempting to authenticate. Since we're supporting older versions of the LTM that don't accept an auth token, we want to know the LTM version so we can decide which auth method to use. An LTM with AD integration doesn't let us perform an unauthenticated GET to retrieve the version. I'll probably just wrap the auth token request in a Try-Catch and fall back to basic auth if that fails. The alternative would be to make the LTM / REST API version a required param for a new session.

**Comment by chrissmullins** [comment] 2017-01-09 15:18
Thanks Joel, sounds good.  I really appreciate the PS library, we are creating new environments and have created hundreds of virtual servers/pools with it!

**Comment by joel74** [comment] 2017-01-23 19:49
Hi, Chris,

When you get a chance, could you please confirm that New-F5Session works for you with the latest commit? If so, then I'll close this issue.

Thanks,
Joel

**Comment by chrissmullins** [comment] 2017-01-24 02:02
Hey Joel,

Yes, it works fine, thanks for fixing…

**Comment by joel74** [comment] 2017-01-24 15:15
Glad to hear it, Chris. Thanks for verifying.

**Closed by joel74** 2017-01-24 15:15 UTC
