### ISSUE TITLE
Get-PoolMemberStats does not seem to work properly

### ISSUE THREAD

**Issue by wrapsbear** [joel74/POSH-LTM-Rest#110] opened 2017-04-11 16:01 UTC
_Caveat:  I am trying this with a v13.0 BIG-IP system, however the release notes don't mention any API changes for v13 and everything else seems to work_

I've been trying to understand the output from Get-PoolMemberStats

Background:  Get-CurrentConnectionCount throws a deprecated warning recommending to use Get-PoolMemberStats and expand the serverside.currConns property, but then also states, "Select-Object : Property "serverside.curConns" cannot be found" and returns an error.

Here's me getting a pool (just for exposition), then getting and piping the pool member to Get-PoolMemberStats. 

```
PS C:\WINDOWS\system32> Get-PoolMember -PoolName /Common/TEST_pl

Name        Partition Address        Description Monitor Session      State
----        --------- -------        ----------- ------- -------      -----
TESTNODE:80 Common    192.168.10.233             default user-enabled unchecked


PS C:\WINDOWS\system32> Get-PoolMember -PoolName /Common/TEST_pl -Address 192.168.10.233

Name        Partition Address        Description Monitor Session      State
----        --------- -------        ----------- ------- -------      -----
TESTNODE:80 Common    192.168.10.233             default user-enabled unchecked


PS C:\WINDOWS\system32> Get-PoolMember -PoolName /Common/TEST_pl -Address 192.168.10.233|Get-PoolMemberStats -verbose
VERBOSE: GET
https://bigip1.company.com/mgmt/tm/ltm/pool/~Common~TEST_pl/members/~Common~TESTNODE:80/stats?ver=13.0.0
with 0-byte payload
VERBOSE: received 1405-byte response of content type application/json

https://localhost/mgmt/tm/ltm/pool/~Common~TEST_pl/members/~Common~TESTNODE:80/~Common~TESTNODE:80/stats
--------------------------------------------------------------------------------------------------------
@{nestedStats=}
```
Am I just terrible at Powershell (I can't figure out whether that hashtable actually has data in it somewhere) or is this broken on v13?

**Comment by joel74** [comment] 2017-04-12 13:34
Hi, wrapsbear, no, it's not your PowerShell use. There is a known issue with pool member stats between versions 11.X and 12 and higher. Please check out the open issue #61. The problem I've been having with this is that the changes to the stats structure aren't clearly defined anywhere. Here's the word from Joe Pruitt at F5:

"Stats are an issue for us as it’s not tied to our schema so we don’t have an easy way to automate how things are changed from release to release.  We are striving to make all the stats follow our deprecation model where they are additive and older stats still persist upon upgrades.  We are working on a new framework with OData support and likely stats will be improved when that goes out.  We are shooting for 13.1.0 but it’s looking like it might slip to 14.0.0.  About 50-50 on it right now"

I have a feeling that handling pool member stats is going to cause the PS module to have to differentiate between supported LTM versions and respond differently based on the version.

**Comment by joel74** [comment] 2017-04-12 13:43
Closing this as a dupe of #61

**Closed by joel74** 2017-04-12 13:43 UTC
